# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rizky Prasetyo
title: Junior Web Programming
email: emailrizkyprasetyo@gmail.com
website: www.teraselektronik.id

# Social links
#twitter_username: facespic
github_username:  rprasetyo
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rprasetyo10
linkedin_username: rizky-prasetyo-a4709b85
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rizky and I'm a Junior Web Progamming. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  An experienced software engineer especially in frontend and backend side.
  Having deep knowledge in HTML, CSS (with its pre-processor) and JavaScript with the various framework. Write good quality, well tested, and fast delivered code.
  Experience in architecting frontend codebase.
  A well-known figure in the programming community, open-source creator, and writer for many technical articles.

  I am most skilled in: <mark>Web</mark> and <mark>Developer</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
